common:
    commitBatchSize: 20
    eventType: DOMAIN-5-TC_PATH_CHG,DOMAIN-5-TCA
    sevOneUrl: http://19.19.19.111:80
    
---
spring:
    profiles: dev
dbConnection:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//uiiomtd1scan.vzbi.com:1800/TIPSM1
    userName: sbhomta11_sit
    password: sbhomta11_sit
common:
    monitorFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/
    archiveFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/Archive
    sevOneUrl: http://localhost:8080
    
---
spring:
    profiles: sit
dbConnection:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//uiiomtd1scan.vzbi.com:1800/TIPSM1
    userName: sbhomta11_sit
    password: sbhomta11_sit    
common:
    monitorFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/
    archiveFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/Archive

---
spring:
    profiles: uat
dbConnection:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//uiiomtd1scan.vzbi.com:1800/TIPSM1
    userName: sbhomta11_sit
    password: sbhomta11_sit
common:
    monitorFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/
    archiveFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/Archive
    
---
spring:
    profiles: lab
dbConnection:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//uiiomtd1scan.vzbi.com:1800/TIPSM1
    userName: sbhomta11_sit
    password: sbhomta11_sit    
common:
    monitorFolder: /home/sevone/syslog
    archiveFolder: /home/sevone/syslog/archieve
            
---
spring:
    profiles: prod
dbConnection:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//uiiomtd1scan.vzbi.com:1800/TIPSM1
    userName: sbhomta11_sit
    password: sbhomta11_sit
common:
    monitorFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/
    archiveFolder: C:/Backup/Desktop/Q2C/2016/SDWAN/sdwan/Archive        

